### ISSUE TITLE
pxbabel と otf パッケージの併用でゴシック体

### ISSUE THREAD

**Issue by aminophen** [zr-tex8r/PXbase#1]
標記のように pxbabel と otf を併用すると，\gtfamily がゴシック体になりません。片方だけだともちろん正常に明朝とゴシックが切り替わります。

~~~~ tex
\documentclass[a4paper,uplatex]{jsarticle}
\usepackage{otf}
\pagestyle{empty}
\usepackage[english]{babel}
\usepackage[main=japanese]{pxbabel}

\def\BOX{\vrule height10pt}

\long\def\TESTJP{%
  日本語Japanese\par
  \BOX 一一一「おはよう、ありがとう」。壱壱壱\BOX\par
  \BOX 二二二『ちょっと，（チェック．）しちゃった！』弐弐弐\BOX\par
  \BOX 三三三“髙島屋と葛飾区”参参参\BOX\par % <= quote
  \BOX 四四四‘（骨曜）’肆肆肆\BOX\par % <= quote
}
\begin{document}

\mcfamily\TESTJP
\gtfamily\TESTJP

\end{document}
~~~~

一瞬，先日の \kanjiencodingdefault の修正の副作用かと思ったのですが，思い返してみるとそれより前からあった挙動のような曖昧な記憶があります。

**Comment by zr-tex8r** [comment]
コレの件、ですね。

* http://oku.edu.mie-u.ac.jp/tex/mod/forum/discuss.php?d=1504

**Comment by zr-tex8r** [comment]
何れにしても「仕様をどうするか」が問題。

 1. 日本語の和文フォントはupjpnrm-h（pxbabel）かuphminr-h（japanese-otf）か。
 2. 日本語のエンコーディングはJ20/J30（またはJ24/J34；pxbabel）かJY2/JT2（japanese-otf）か。
 3. 日本語の総称ファミリはmc（pxbabel）かhmc（japanese-otf）か。
 4. 中国語・韓国語の総称ファミリはmcかhmcか。

**Comment by aminophen** [comment]
たしかにフォーラムにもあったのですね…

仕様は悩みますが，[TeX.SX](https://tex.stackexchange.com/questions/374838/why-do-uplatex-display-chinese-text-with-japanese-punctations-instead-of-chinese) のようなケースで LaTeX ユーザ向けの対処は pxbabel しか現時点ではないので，決めておきたいとは思います。（本来だったら upLaTeX カーネルでサポートしたほうがいいのだと思いますが。）issue を立てた側としても後で考えてみます。

**Comment by zr-tex8r** [comment]
* アレフォーラムの質問者は「otfパッケージを読みこんだから、otfのメトリックになっていて、otfの`jis2004`が効く」と期待している。至極当然である。
  * otfの動作を変えようとするより、pxbabelの動作を変える方が明らかに容易である。

ということを考慮すると：

1.  日本語の和文フォントはupjpnrm-h（pxbabel）かuphminr-h（japanese-otf）か。  
    japanese-otfのフォントでないと「期待に沿わない」ことになる。
2.  日本語のエンコーディングはJ20/J30（またはJ24/J34；pxbabel）かJY2/JT2（japanese-otf）か。  
    japanese-otfのフォントのエンコーディングを変えたくないので、JY2/JT2。
3.  日本語の総称ファミリはmc（pxbabel）かhmc（japanese-otf）か。  
    japanese-otfのフォントのファミリは変えたくないのでhmc。
4.  中国語・韓国語の総称ファミリはmcかhmcか。  
    そもそもjapanese-otfは`\mcdefault`をhmcに変えている。とすると、pxbabelが`\mcdefault`を見ずに常に明朝体をmcとしているのが筋が悪い気がする。

従って、仕様は：

  * pxbabelが J2?/mc/m/n を定義するのは従来通り。
  * `\mcdefault`がmcでない場合は、J2?/mc を J2?/`\mcdefault` にコピーする。
  * `japanese`のエンコーディングをJY2のままにするオプション`stdjaencoding`を設ける。
  * 「標準の和文フォントが変更されている」に相当する何らかの条件〠を決めておいて、条件〠が成り立つ場合に`stdjaencoding`を既定で有効にする。  
    （恐らく〠も「`\mcdefault`がmcでない」でいいと思う。）
  * ゴシックおよび縦組フォントについても全く同様。

ですかね…。

**Comment by aminophen** [comment]
なるほど、筋が通っていると思います。可能ならばそのようにしていただけると…

**Comment by zr-tex8r** [comment]
ソレを実装してみた（v1.1b 5bfbee2 ）。
